version: '3.8'

services:
  notifications:
    container_name: "notifications"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - ./app:/app
    # environment:
    #   - NODE_ENV=production
    env_file:
      - .env
