version: '3.8'

services:
  notifications:
    container_name: "notifications"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - ./app:/app
    env_file:
      - .env

volumes:
  app:
    driver: local
